name: floodnet-client
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip>=20.0
  # Core dependencies
  - requests>=2.28.0
  - pydantic>=2.0.0
  # Spatial dependencies
  - geopandas>=0.10.0
  - shapely>=2.0.0
  # Development dependencies
  - pytest
  - pip:
    - -e .  # Install package in editable mode
